#!/bin/bash

colors="$HOME/.cache/wal/colors.json"
output="$HOME/.config/hypr/colors.conf"

# Always use "aa" as the alpha suffix
alpha="aa"

# Function to convert hex to rgba(rrggbbaa)
hex_to_rgba() {
    hex="$1"
    hex_clean="${hex:1}"  # remove leading #
    hex_lower=$(echo "$hex_clean" | tr '[:upper:]' '[:lower:]')
    echo "rgba(${hex_lower}${alpha})"
}

{
  echo "# Generated by pywal_hypr.sh"
  echo "# Format: \$name = rgba(rrggbbaa)"
  echo "# Alpha is hardcoded: $alpha"

  # Special colors
  jq -r '.special | to_entries[] | "\(.key) \(.value)"' "$colors" | while read -r key value; do
    echo "\$$key = $(hex_to_rgba "$value")"
  done

  # Base colors
  jq -r '.colors | to_entries[] | "\(.key) \(.value)"' "$colors" | while read -r key value; do
    echo "\$$key = $(hex_to_rgba "$value")"
  done

} > "$output"
