"$schema" = 'https://starship.rs/config-schema.json'

format = """ $os $username $directory """
right_format = """$git_branch$python"""
add_newline = false
palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '#cac8ad'
color2 = '#31311f'
color3 = '#c9c6c2'
color4 = '#20201d'
color5 = '#31311f'
color6 = '#141311'
color7 = '#141311'
color8 = '#cac8ad'
color9 = '#cac8a5'
color10 = '#d7adc7'
global_color = '#ffb7c7aa'
global_color2 = '#ffb7c700'

[os]
disabled = false
style = "fg:global_color"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:global_color"
style_root = "fg:global_color"
format = '[ $user ]($style)'

[directory]
format = "[  ](fg:global_color2)[ $path]($style)(fg:global_color2)"
style = "fg:global_color2"
truncation_length = 0
truncation_symbol = ""
use_logical_path = true

[character]
success_symbol = "[󱪁](blue bold)"
error_symbol = "[󱪁](red bold)"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:global_color2"
symbol = " "

[git_branch]
format = "(fg:global_color2)[ $symbol $branch]($style)(fg:global_color2)"
style = "fg:green"
symbol = ""

[time]
disabled = false
format = "(fg:overlay)[ $time 󰴈 ]($style)(fg:overlay)"
style = "fg:gold"
time_format = "%H:%M"
use_12hr = false

[python]
detect_extensions=[]
style = 'fg:yellow'
symbol = ' '
format = ' [${symbol}$virtualenv]($style)'
